# Notebook 1 – Data Preprocessing Fundamentals

### Objective

To understand the fundamentals of data preprocessing and learn how raw data is converted into clean, consistent, validated, and machine-learning-ready data.

### Topics Covered

- What is Data Preprocessing?
- Why is Data Preprocessing Required?
- Raw Data vs Clean Data
- Data Quality
- Data Consistency
- Data Completeness
- Data Accuracy
- Data Validity
- Data Integrity
- Data Leakage
- Training Data
- Validation Data
- Test Data
- Preprocessing Pipeline
- Complete Data Preprocessing Workflow

# 1.What is Data Preprocessing?

## Step 1 – Understand the Concept

Data preprocessing is the process of preparing raw data before using it for analysis or Machine Learning.

Real-world data may contain:

- Missing values
- Duplicate records
- Incorrect data types
- Inconsistent values
- Invalid values
- Outliers
- Categorical values
- Irrelevant features

The main goal of data preprocessing is to convert raw data into clean, consistent, validated, and ML-ready data.

### Main Process

Raw Data → Clean Data → Transform Data → Validate Data → ML-Ready Data

## Step 2 – Demonstrate the Concept

### Simple Example

A dataset may contain:

- Age = 25
- Age = NaN
- Gender = "Male"
- Gender = "male"
- Salary = "50000"

Here, the dataset contains a missing value, inconsistent category representation, and a numerical value stored as text.

### Real-World Example

In a telecom customer dataset, customer information may contain missing charges, duplicate customers, inconsistent categories, and incorrect data types.

### AI/ML Use Case

Before training a customer churn prediction model, these issues must be handled so that the model receives reliable input data.

### Why is preprocessing required?

Poor-quality data can lead to incorrect analysis and poor Machine Learning performance.



## Step 3 – Implement the Concept

In [1]:
import pandas as pd
import numpy as np

data = {
    "Age": [25, 30, np.nan, 28],
    "Gender": ["Male", "Female", "female", "Male"],
    "Salary": ["30000", "45000", "50000", "60000"]
}

df = pd.DataFrame(data)

df

    Age  Gender Salary
0  25.0    Male  30000
1  30.0  Female  45000
2   NaN  female  50000
3  28.0    Male  60000

## Result / Observation

The raw dataset contains:

- Missing Age value
- Inconsistent Gender values
- Salary stored as a string

These issues show why data preprocessing is required before Machine Learning.

# 2. Why is Data Preprocessing Required?


## Step 1 – Understand the Concept

Data preprocessing is required because real-world data is rarely perfect.

Data may contain:

- Missing values
- Duplicate records
- Invalid values
- Incorrect data types
- Inconsistent categories
- Outliers
- Different numerical scales
- Irrelevant features

If these problems are ignored, they can affect analysis and Machine Learning performance.

### Main Objectives

- Improve data quality
- Make data consistent
- Handle missing values
- Correct data types
- Validate values
- Prepare features for ML algorithms
- Reduce the risk of data leakage

## Step 2 – Demonstrate the Concept

### Real-World Example

Consider a customer churn dataset.

If MonthlyCharges contains missing values, Contract contains inconsistent categories, and tenure is stored as text, the dataset is not ready for Machine Learning.

### Business Example

A telecom company wants to predict customers who may leave.

If the input data is incorrect, the company may incorrectly identify customers as high-risk or low-risk.

### AI/ML Impact

Poor preprocessing can cause:

- Incorrect patterns
- Poor model performance
- Unstable predictions
- Incorrect business decisions

Therefore, preprocessing is an important part of the ML workflow.


## Step 3 – Implement the Concept

In [2]:
# Check common data-quality problems

print("Missing Values:")
print(df.isnull().sum())

print("\nData Types:")
print(df.dtypes)

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Missing Values:
Age       1
Gender    0
Salary    0
dtype: int64

Data Types:
Age       float64
Gender     object
Salary     object
dtype: object

Duplicate Rows:
0

## Result / Observation

The inspection helps identify problems before applying preprocessing techniques.

Data should be inspected first instead of blindly applying cleaning operations.

# 3. Raw Data vs Clean Data


## Step 1 – Understand the Concept

### Raw Data

Raw data is the original data collected from different sources before cleaning.

It may contain:

- Missing values
- Duplicates
- Incorrect formats
- Invalid values
- Inconsistent categories
- Incorrect data types

### Clean Data

Clean data has been checked, validated, and appropriately processed.

It should contain:

- Appropriate data types
- Valid values
- Consistent categories
- Properly handled missing values
- Investigated duplicates
- Suitable structure for further analysis or ML

## Step 2 – Demonstrate the Concept

### Raw Data Example

| Age | Gender | Salary |
|---:|---|---|
| 25 | Male | 30000 |
| NaN | female | "40000" |
| -5 | M | 50000 |

Problems:

- Missing Age
- Inconsistent Gender
- Salary stored as text
- Negative Age

### Clean Data Example

After appropriate preprocessing:

| Age | Gender | Salary |
|---:|---|---:|
| 25 | Male | 30000 |
| Appropriate value | Female | 40000 |
| Validated value | Male | 50000 |

The exact treatment should depend on the reason for the problem and the dataset.



## Step 3 – Implement the Concept

In [3]:
raw_data = pd.DataFrame({
    "Age": [25, np.nan, -5],
    "Gender": ["Male", "female", "M"],
    "Salary": ["30000", "40000", "50000"]
})

print("Raw Data:")
display(raw_data)

print("\nData Types:")
print(raw_data.dtypes)

Raw Data:

    Age  Gender Salary
0  25.0    Male  30000
1   NaN  female  40000
2  -5.0       M  50000

Data Types:
Age       float64
Gender     object
Salary     object
dtype: object

## Result / Observation

The raw dataset contains missing, inconsistent, and potentially invalid values.

This shows the difference between collected data and data that is ready for further processing.

# 4. Data Quality


## Step 1 – Understand the Concept

Data quality describes how suitable and reliable a dataset is for its intended purpose.

Important dimensions of data quality include:

- Completeness
- Consistency
- Accuracy
- Validity
- Integrity

Good data quality helps produce reliable analysis and Machine Learning results.

## Step 2 – Demonstrate the Concept

### Business Example

A bank wants to predict whether a customer will repay a loan.

If customer income is incorrect, age is missing, or employment information is inconsistent, the model may make unreliable predictions.

### AI/ML Use Case

Before model training, engineers should examine whether the dataset is:

- Complete
- Consistent
- Accurate
- Valid
- Reliable

Data quality problems should be identified before modeling.


## Step 3 – Implement the Concept

In [4]:
quality_data = pd.DataFrame({
    "Age": [25, np.nan, 30],
    "Salary": [30000, 40000, -5000],
    "Gender": ["Male", "Female", "female"]
})

print("Missing Values:")
print(quality_data.isnull().sum())

print("\nDuplicate Rows:")
print(quality_data.duplicated().sum())

print("\nData Types:")
print(quality_data.dtypes)

Missing Values:
Age       1
Salary    0
Gender    0
dtype: int64

Duplicate Rows:
0

Data Types:
Age       float64
Salary      int64
Gender     object
dtype: object

## Result / Observation

Basic inspection can identify some data-quality issues.

Further validation is required to determine whether values are accurate, valid, and consistent.

# 5. Data Consistency


## Step 1 – Understand the Concept

Data consistency means representing the same type of information in a uniform way.

For example, the same gender category should not be represented as:

- Male
- male
- M
- MALE

Inconsistent categories can create unnecessary categories during analysis and encoding.

## Step 2 – Demonstrate the Concept

### Simple Example

Suppose a dataset contains:

```text
Male
male
M
MALE

## Step 3 – Implement the Concept

In [6]:


consistency_df = pd.DataFrame({
    "Gender": ["Male", "male", "M", "Female", "female", "F"]
})

print("Before Standardization:")
print(consistency_df["Gender"].unique())

consistency_df["Gender"] = consistency_df["Gender"].replace({
    "male": "Male",
    "M": "Male",
    "female": "Female",
    "F": "Female"
})

print("\nAfter Standardization:")
print(consistency_df["Gender"].unique())

Before Standardization:
['Male' 'male' 'M' 'Female' 'female' 'F']

After Standardization:
['Male' 'Female']

## Result / Observation

The categorical values were standardized into consistent categories.

This reduces unnecessary category variations before encoding.

# 6. Data Completeness


## Step 1 – Understand the Concept

Data completeness refers to whether the required information is available.

A dataset is incomplete when important values are missing.

Missing data can occur because:

- A value was not collected
- A user did not provide information
- A system failed to record the value
- Data was lost during transfer
- A particular field was not applicable

## Step 2 – Demonstrate the Concept

### Example

A customer dataset contains:

| Customer | Age | Salary |
|---|---:|---:|
| A | 25 | 30000 |
| B | NaN | 40000 |
| C | 30 | NaN |

The dataset is incomplete because Age and Salary have missing values.

### Business Impact

If Salary is an important feature for a prediction model, missing salary values may affect the model's ability to learn useful patterns.

Therefore, missing values should be analyzed before deciding whether to:

- Remove rows
- Remove columns
- Impute values
- Use another missing-value technique


## Step 3 – Implement the Concept

In [7]:
completeness_df = pd.DataFrame({
    "Age": [25, np.nan, 30, 35],
    "Salary": [30000, 40000, np.nan, 50000]
})

missing_count = completeness_df.isnull().sum()
missing_percentage = completeness_df.isnull().mean() * 100

print("Missing Value Count:")
print(missing_count)

print("\nMissing Value Percentage:")
print(missing_percentage)

Missing Value Count:
Age       1
Salary    1
dtype: int64

Missing Value Percentage:
Age       25.0
Salary    25.0
dtype: float64

## Result / Observation

The missing-value count and percentage help us understand the completeness of each feature.

The appropriate treatment will depend on the amount and reason for missing data.

# 7. Data Accuracy

## Step 1 – Understand the Concept

Data accuracy means that the recorded value correctly represents the real-world value.

A value can be present but still be inaccurate.

### Example

Actual age = 25

Recorded age = 250

The value is not missing, but it is inaccurate.

Therefore, checking only for missing values does not guarantee data accuracy.

## Step 2 – Demonstrate the Concept

### Business Example

Suppose a telecom customer actually has a MonthlyCharges value of ₹70, but the system records ₹700.

The value exists, but it may be inaccurate.

### AI/ML Impact

An inaccurate feature can cause the model to learn incorrect relationships.

Therefore, data should be compared with:

- Business rules
- Source systems
- Expected ranges
- Trusted reference data


## Step 3 – Implement the Concept

In [8]:
accuracy_df = pd.DataFrame({
    "Customer": ["A", "B", "C"],
    "Age": [25, 250, 35]
})

# Identify suspicious ages
suspicious = accuracy_df[
    (accuracy_df["Age"] < 0) |
    (accuracy_df["Age"] > 100)
]

print("Suspicious Records:")
display(suspicious)

Suspicious Records:

  Customer  Age
1        B  250

## Result / Observation

The value 250 is suspicious for an Age feature.

It should not be automatically deleted. The source of the value should be investigated before deciding how to handle it.

# 8. Data Validity


## Step 1 – Understand the Concept

Data validity means that values follow the expected format, range, data type, and business rules.

Examples:

- Age should not be negative.
- Percentage should be between 0 and 100.
- Salary should not be negative.
- Gender should belong to accepted categories.
- Dates should follow a valid date format.

## Step 2 – Demonstrate the Concept

### Business Example

A company stores employee performance percentages.

Valid values:

0 to 100


### AI/ML Impact

Invalid values can distort:
- Statistical analysis
- Feature distributions
- Model training
- Predictions
Therefore, validation rules should be defined before using the data.


## Step 3 – Implement the Concept

In [10]:



validation_df = pd.DataFrame({
    "Employee": ["A", "B", "C", "D"],
    "Performance": [85, 110, -5, 75]
})

invalid_records = validation_df[
    (validation_df["Performance"] < 0) |
    (validation_df["Performance"] > 100)
]

print("Invalid Performance Values:")
display(invalid_records)

Invalid Performance Values:

  Employee  Performance
1        B          110
2        C           -5

## Result / Observation

Values outside the accepted range were identified.

Validation helps detect invalid records before they affect analysis or Machine Learning.

# 9. Data Integrity


## Step 1 – Understand the Concept

Data integrity means maintaining the correctness, consistency, and reliability of data throughout its lifecycle.

Integrity is important when data is:

- Collected
- Stored
- Updated
- Transferred
- Combined
- Processed

### Example

A Customer_ID should correctly identify the intended customer.

If the same ID is incorrectly assigned to different customers, data integrity may be affected.

## Step 2 – Demonstrate the Concept

### Business Example

Suppose a customer table contains:

| Customer_ID | Name |
|---|---|
| C001 | Arun |
| C002 | Priya |

A transaction table should reference valid customer IDs.

If a transaction contains Customer_ID = C999 but C999 does not exist in the customer table, there may be a referential integrity problem.

### AI/ML Impact

Incorrect relationships between datasets can result in incorrect features and unreliable predictions.



## Step 3 – Implement the Concept

In [11]:
customers = pd.DataFrame({
    "Customer_ID": ["C001", "C002", "C003"]
})

transactions = pd.DataFrame({
    "Customer_ID": ["C001", "C002", "C999"],
    "Amount": [500, 700, 900]
})

valid_ids = set(customers["Customer_ID"])

invalid_transactions = transactions[
    ~transactions["Customer_ID"].isin(valid_ids)
]

print("Transactions with Invalid Customer IDs:")
display(invalid_transactions)

Transactions with Invalid Customer IDs:

  Customer_ID  Amount
2        C999     900

## Result / Observation

Customer_ID = C999 does not exist in the customer table.

This demonstrates how referential integrity can be checked before combining datasets.

# 10. Data Leakage


## Step 1 – Understand the Concept

Data leakage occurs when information that should not be available during model training becomes available to the Machine Learning model.

This can produce unrealistically high evaluation performance.

### Common Types

- Target leakage
- Train-test contamination
- Feature leakage
- Preprocessing leakage
- Temporal leakage

### Important Rule

Information from validation or test data should not influence the training process.

## Step 2 – Demonstrate the Concept

### Customer Churn Example

Suppose we want to predict whether a customer will churn.

If we use a feature that is created after the customer has already cancelled the service, the model receives future information.

This is target leakage.

### Preprocessing Leakage Example

Suppose we calculate the mean of a feature using the entire dataset and then split the data.

The test data has influenced the preprocessing value.

### Correct Approach


Split Data

    ↓
    
Fit preprocessing on Training Data

    ↓
    
Transform Training Data

    ↓
    
Transform Validation/Test Data


### AI/ML Impact
Data leakage can make a model appear highly accurate during testing but perform poorly on real-world unseen data.


## Step 3 – Implement the Concept

In [13]:



from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

leakage_df = pd.DataFrame({
    "Feature": [10, 20, 30, 40, 50, 60, 70, 80],
    "Target": [0, 0, 0, 1, 1, 1, 1, 1]
})

X = leakage_df[["Feature"]]
y = leakage_df["Target"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

scaler = StandardScaler()

# Fit only on training data
X_train_scaled = scaler.fit_transform(X_train)

# Use the same fitted scaler on test data
X_test_scaled = scaler.transform(X_test)

print("Training Data:")
print(X_train_scaled)

print("\nTest Data:")
print(X_test_scaled)

Training Data:
[[-1.55563492]
 [ 1.41421356]
 [-0.70710678]
 [ 0.14142136]
 [-0.28284271]
 [ 0.98994949]]

Test Data:
[[-1.13137085]
 [ 0.56568542]]

# 11. Training Data


## Step 1 – Understand the Concept

Training data is the portion of the dataset used to train a Machine Learning model.

The model learns patterns and relationships from the training data.

For example, in customer churn prediction, the model may learn relationships between:

- Tenure
- MonthlyCharges
- Contract
- PaymentMethod
- Churn

## Step 2 – Demonstrate the Concept

### Example

Suppose we have 1,000 customer records.

A possible split is:


Training Data     = 700 records

Validation Data   = 150 records

Test Data         = 150 records


The training data is used to learn the model.

### Important
Preprocessing parameters such as:
- Mean
- Median
- Scaling parameters
- Encoding mappings
- Feature selection parameters
should be learned from the training data.


## Step 3 – Implement the Concept

In [15]:



from sklearn.model_selection import train_test_split

X = pd.DataFrame({
    "Age": [21, 25, 30, 35, 40, 45, 50, 55],
    "Salary": [25000, 30000, 35000, 40000, 45000, 50000, 55000, 60000]
})

y = pd.Series([0, 0, 0, 1, 1, 1, 1, 1])

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

print("Training Data:")
display(X_train)

print("Training Data Shape:", X_train.shape)

Training Data:

   Age  Salary
0   21   25000
7   55   60000
2   30   35000
4   40   45000
3   35   40000
6   50   55000

Training Data Shape: (6, 2)

## Result / Observation

The training dataset contains the records used for learning the Machine Learning model.

The `random_state` makes the split reproducible.

# 12. Validation Data


## Step 1 – Understand the Concept

Validation data is used during Machine Learning development to evaluate model choices before final testing.

It can be used for:

- Hyperparameter tuning
- Model comparison
- Selecting preprocessing approaches
- Choosing between different algorithms

The validation dataset should remain separate from the training process.

## Step 2 – Demonstrate the Concept

### Example

Suppose we have 1,000 records:


Training   = 700

Validation = 150

Test       = 150

The model learns from training data.

Different model configurations can be compared using validation data.

The final selected model is then evaluated on the test dataset.

### Why?
If we repeatedly use the test data to make model decisions, the test data is no longer an unbiased final evaluation set.


## Step 3 – Implement the Concept

In [16]:


from sklearn.model_selection import train_test_split

X_temp, X_test, y_temp, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42
)

X_train, X_validation, y_train, y_validation = train_test_split(
    X_temp,
    y_temp,
    test_size=0.25,
    random_state=42
)

print("Training Shape:", X_train.shape)
print("Validation Shape:", X_validation.shape)
print("Test Shape:", X_test.shape)

Training Shape: (4, 2)
Validation Shape: (2, 2)
Test Shape: (2, 2)

## Result / Observation

The dataset has been divided into three subsets:

- Training data
- Validation data
- Test data

The validation data can be used during model development without using the final test set for tuning.

# 13. Test Data

## Step 1 – Understand the Concept

Test data is used to evaluate the final Machine Learning model on unseen data.

The test dataset should represent data that the model has not used during:

- Training
- Preprocessing fitting
- Feature selection decisions
- Hyperparameter tuning

The purpose is to estimate how the final model may perform on new real-world data.

## Step 2 – Demonstrate the Concept

### Example

Suppose a customer churn dataset contains 10,000 records.

A possible split is:


Training   → 7,000

Validation → 1,500

Test       → 1,500


The final model is evaluated using the test data after model development is complete.

### Important Rule
The test data should not be used to make repeated model decisions.

Otherwise, the final evaluation may become overly optimistic.

In [17]:


# Display the test dataset created during the splitting process

print("Test Features:")
display(X_test)

print("Test Target:")
display(y_test)

print("Test Data Shape:", X_test.shape)

Test Features:

   Age  Salary
1   25   30000
5   45   50000

Test Target:

1    0
5    1
dtype: int64

Test Data Shape: (2, 2)

## Result / Observation

The test dataset is kept separate from the training and validation datasets.

It can be used for final evaluation of the selected Machine Learning model.

# 14. Preprocessing Pipeline

## Step 1 – Understand the Concept

A preprocessing pipeline is an organized sequence of preprocessing steps that are applied consistently to data.

A typical Machine Learning preprocessing pipeline may include:

1. Missing value imputation
2. Categorical encoding
3. Numerical scaling
4. Feature transformation
5. Feature selection

A pipeline makes preprocessing:

- Consistent
- Reproducible
- Easier to maintain
- Less error-prone
- Safer against data leakage

### Important Principle

The preprocessing steps should be fitted using training data and then applied to validation and test data.

## Step 2 – Demonstrate the Concept

### Real-World Example

Consider a telecom customer churn dataset.

Numerical features:

- Tenure
- MonthlyCharges
- TotalCharges

Categorical features:

- Contract
- InternetService
- PaymentMethod

A preprocessing pipeline can handle them differently.

### Numerical Pipeline


Missing Value Imputation

        ↓
        
    Scaling


## Step 3 – Implement the Concept

In [18]:



from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

pipeline_df = pd.DataFrame({
    "Age": [25, 30, np.nan, 40],
    "Salary": [30000, 40000, 50000, np.nan],
    "Gender": ["Male", "Female", "Female", "Male"]
})

X_pipeline = pipeline_df.copy()

numeric_features = ["Age", "Salary"]
categorical_features = ["Gender"]

numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("encoder", OneHotEncoder(handle_unknown="ignore"))
])

preprocessing_pipeline = ColumnTransformer([
    ("numeric", numeric_pipeline, numeric_features),
    ("categorical", categorical_pipeline, categorical_features)
])

X_transformed = preprocessing_pipeline.fit_transform(X_pipeline)

print("Original Shape:", X_pipeline.shape)
print("Transformed Shape:", X_transformed.shape)

Original Shape: (4, 3)
Transformed Shape: (4, 4)

## Result / Observation

The preprocessing pipeline performed multiple transformations:

### Numerical Features

- Missing values were handled using median imputation.
- Numerical values were standardized using StandardScaler.

### Categorical Features

- Missing values were handled using the most frequent value.
- Categorical values were converted into numerical representation using One-Hot Encoding.

The transformations were combined using `ColumnTransformer`.

This creates a structured preprocessing workflow that can later be connected directly to a Machine Learning model.

# 15. Complete Data Preprocessing Workflow


## Step 1 – Understand the Concept

A complete preprocessing workflow converts raw data into reliable ML-ready data.

### Workflow

1. Load the dataset
2. Inspect the dataset
3. Understand the features and target
4. Identify data types
5. Identify missing values
6. Identify duplicate records
7. Check data consistency
8. Validate data
9. Detect outliers
10. Decide how to treat outliers
11. Split data into training, validation, and test sets
12. Fit preprocessing using training data
13. Handle missing values
14. Encode categorical features
15. Scale or transform numerical features
16. Select useful features
17. Handle class imbalance where applicable
18. Validate the processed data
19. Generate ML-ready data
20. Train the Machine Learning model

## Step 2 – Demonstrate the Concept

### Example – Telecom Customer Churn

A telecom company wants to predict customer churn.

### Raw Dataset

The dataset may contain:

- Missing values
- Duplicate customers
- Numerical features
- Categorical features
- Outliers
- Inconsistent categories
- Different data types

### Preprocessing Workflow

```text
Raw Telco Dataset
        ↓
Dataset Inspection
        ↓
Data Quality Assessment
        ↓
Data Type Handling
        ↓
Missing Value Handling
        ↓
Duplicate Handling
        ↓
Data Validation
        ↓
Outlier Analysis
        ↓
Train / Validation / Test Split
        ↓
Numerical Preprocessing
        ↓
Categorical Preprocessing
        ↓
Feature Selection
        ↓
Class Imbalance Handling
        ↓
Final Validation
        ↓
ML-Ready Dataset
        ↓
Machine Learning Model

### Important
Not every dataset requires every preprocessing technique.

The technique should be selected based on the actual problem found in the dataset.

**For example:**
- If there are no missing values, imputation may not be required.
- If outliers are valid business observations, they should not automatically be removed.
- If an algorithm is not sensitive to feature scale, scaling may not always be necessary.


## Step 3 – Implement the Concept

In [19]:


# Simple demonstration of a preprocessing workflow

import pandas as pd
import numpy as np

workflow_df = pd.DataFrame({
    "Age": [25, 30, np.nan, 40, 35],
    "Salary": [30000, 40000, 50000, np.nan, 60000],
    "Gender": ["Male", "Female", "Female", "Male", "Female"]
})

# 1. Inspect
print("Initial Shape:", workflow_df.shape)

# 2. Check missing values
print("\nMissing Values:")
print(workflow_df.isnull().sum())

# 3. Check duplicates
print("\nDuplicate Rows:", workflow_df.duplicated().sum())

# 4. Check data types
print("\nData Types:")
print(workflow_df.dtypes)

# 5. Handle missing numerical values
workflow_df["Age"] = workflow_df["Age"].fillna(
    workflow_df["Age"].median()
)

workflow_df["Salary"] = workflow_df["Salary"].fillna(
    workflow_df["Salary"].median()
)

# 6. Validate the final basic structure
print("\nMissing Values After Basic Cleaning:")
print(workflow_df.isnull().sum())

print("\nFinal Dataset:")
display(workflow_df)

Initial Shape: (5, 3)

Missing Values:
Age       1
Salary    1
Gender    0
dtype: int64

Duplicate Rows: 0

Data Types:
Age       float64
Salary    float64
Gender     object
dtype: object

Missing Values After Basic Cleaning:
Age       0
Salary    0
Gender    0
dtype: int64

Final Dataset:

    Age   Salary  Gender
0  25.0  30000.0    Male
1  30.0  40000.0  Female
2  32.5  50000.0  Female
3  40.0  45000.0    Male
4  35.0  60000.0  Female

## Result / Observation

The workflow demonstrated the basic stages of preprocessing:

- Dataset inspection
- Missing-value detection
- Duplicate detection
- Data-type inspection
- Missing-value handling
- Final validation

The dataset is now cleaner and can move to further preprocessing steps such as encoding, scaling, transformation, feature selection, and Machine Learning.

### Core Principle

**Identify → Analyze → Clean → Transform → Validate → Prepare for Machine Learning**

The purpose of preprocessing is not to blindly change the dataset.

Every preprocessing decision should be based on:

**Problem → Analysis → Technique Selected → Reason → Implementation → Result → ML Impact**

# Notebook 1 – Final Summary

In this notebook, we learned the fundamentals of Data Preprocessing.

### Concepts Covered

- Data Preprocessing
- Need for Data Preprocessing
- Raw Data vs Clean Data
- Data Quality
- Data Consistency
- Data Completeness
- Data Accuracy
- Data Validity
- Data Integrity
- Data Leakage
- Training Data
- Validation Data
- Test Data
- Preprocessing Pipeline
- Complete Preprocessing Workflow

### Key Learning

Raw data is rarely ready for Machine Learning.

A Data Scientist or AI/ML Engineer must first understand the quality and structure of the data, identify problems, select appropriate preprocessing techniques, and validate the results.

### Final Workflow

**Raw Data**
→ **Inspect**
→ **Identify Problems**
→ **Analyze**
→ **Clean**
→ **Transform**
→ **Validate**
→ **Split Data**
→ **Apply Preprocessing**
→ **Feature Selection**
→ **Final Validation**
→ **ML-Ready Data**

Most importantly, preprocessing must be performed carefully to avoid **data leakage** and to ensure that the final Machine Learning model can generalize to unseen data.